<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-06T02:46:22 IST" name="Default suite" finished-at="2022-02-06T02:46:27 IST" duration-ms="5820">
    <groups>
    </groups>
    <test started-at="2022-02-06T02:46:22 IST" name="Default test" finished-at="2022-02-06T02:46:27 IST" duration-ms="5820">
      <class name="practice.RestAssuredTest">
        <test-method signature="GetWeatherDetails()[pri:0, instance:practice.RestAssuredTest@524d6d96]" started-at="2022-02-06T02:46:22 IST" name="GetWeatherDetails" finished-at="2022-02-06T02:46:24 IST" duration-ms="2148" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetWeatherDetails -->
        <test-method signature="post_practice()[pri:0, instance:practice.RestAssuredTest@524d6d96]" started-at="2022-02-06T02:46:24 IST" name="post_practice" finished-at="2022-02-06T02:46:25 IST" duration-ms="1014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- post_practice -->
        <test-method signature="query_parameter()[pri:0, instance:practice.RestAssuredTest@524d6d96]" started-at="2022-02-06T02:46:25 IST" name="query_parameter" finished-at="2022-02-06T02:46:26 IST" duration-ms="1355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- query_parameter -->
        <test-method signature="self_practise()[pri:0, instance:practice.RestAssuredTest@524d6d96]" started-at="2022-02-06T02:46:26 IST" name="self_practise" finished-at="2022-02-06T02:46:27 IST" duration-ms="1265" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<422> but was:<201>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<422> but was:<201>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at org.junit.Assert.assertEquals(Assert.java:456)
at practice.RestAssuredTest.self_practise(RestAssuredTest.java:138)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- self_practise -->
      </class> <!-- practice.RestAssuredTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
